# Generated by Django 4.2.5 on 2023-09-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProcedures',
            fields=[
                ('Procedure_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Procedure_Name', models.CharField(help_text='Input Procedure Name', max_length=128)),
                ('Description', models.TextField()),
                ('Image_URL', models.CharField(max_length=128)),
                ('Price', models.FloatField(max_length=16)),
                ('Status', models.CharField(choices=[('0', 'Удален'), ('1', 'Действует')], default='1', help_text='Status Procedure', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Is_Admin', models.BooleanField(default=False)),
                ('Username', models.CharField(help_text='Input your Username', max_length=48)),
                ('Login', models.CharField(help_text='Input your Login', max_length=48)),
                ('Password', models.CharField(help_text='Input your Password', max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCategories',
            fields=[
                ('MedicalCategories_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(help_text='Input Category Name', max_length=64)),
                ('Description', models.TextField()),
                ('Image_URL', models.CharField(max_length=128)),
                ('Status', models.CharField(choices=[('i', 'Введён'), ('w', 'В работе'), ('e', 'Завершён'), ('c', 'Отменён'), ('d', 'Удалён')], default='i', help_text='Status Category', max_length=1)),
                ('Date_Creation', models.DateField(default='01.01.1900', help_text='Date of receipt of the order')),
                ('Date_Approving', models.DateField(default='01.01.1900', help_text='Date of Approving order')),
                ('Date_End', models.DateField(default='01.01.1900', help_text='Date of End order')),
                ('Moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.users')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesProcedures',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.medicalcategories')),
                ('Procedure_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.medicalprocedures')),
            ],
        ),
    ]
