# Generated by Django 4.2.5 on 2024-01-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_moderator',
            new_name='Is_Super',
        ),
    ]
