# Generated by Django 4.2.5 on 2023-11-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcategories',
            name='ID_Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Author', to='bmstu_lab.users'),
        ),
    ]
