# Generated by Django 4.2.5 on 2023-11-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_medicalcategories_id_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesprocedures',
            name='Number',
            field=models.IntegerField(default=1, help_text='Порядковый номер', null=True),
        ),
        migrations.AddField(
            model_name='medicalcategories',
            name='MedicalProceduresList',
            field=models.ManyToManyField(through='bmstu_lab.CategoriesProcedures', to='bmstu_lab.medicalprocedures'),
        ),
        migrations.AlterField(
            model_name='medicalcategories',
            name='Image_URL',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='medicalprocedures',
            name='Image_URL',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
