# Generated by Django 4.2.5 on 2023-12-12 23:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_alter_categoriesprocedures_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_aid',
            fields=[
                ('First_aid_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_aid_Name', models.CharField(help_text='Input First aid Name', max_length=128)),
                ('Description', models.TextField()),
                ('Image_URL', models.ImageField(blank=True, upload_to='img/')),
                ('Price', models.FloatField(max_length=16)),
                ('Status', models.CharField(choices=[('0', 'Удален'), ('1', 'Действует')], default='1', help_text='Status First aid', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='First_aid_Trauma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(help_text='Sequence Number', null=True)),
                ('First_aid_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.first_aid')),
            ],
        ),
        migrations.CreateModel(
            name='Trauma',
            fields=[
                ('Trauma_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Trauma_Name', models.CharField(help_text='Input Trauma Name', max_length=64)),
                ('Status', models.CharField(choices=[('Draft', 'Черновик'), ('Formed', 'Сформирована'), ('Completed', 'Завершёна'), ('Cancelled', 'Отклонена'), ('Deleted', 'Удалёна')], default='Draft', help_text='Status Trauma', max_length=10)),
                ('Date_Creation', models.DateField(default=datetime.datetime(2023, 12, 12, 23, 51, 40, 626319, tzinfo=datetime.timezone.utc), help_text='Date of Creating of the order (Trauma)')),
                ('Date_Approving', models.DateField(default=datetime.datetime(2023, 12, 12, 23, 51, 40, 626319, tzinfo=datetime.timezone.utc), help_text='Date of Approving (Trauma)')),
                ('Date_End', models.DateField(default=datetime.datetime(2023, 12, 12, 23, 51, 40, 626319, tzinfo=datetime.timezone.utc), help_text='Date of End order (Trauma)')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalcategories',
            name='ID_Creator',
        ),
        migrations.RemoveField(
            model_name='medicalcategories',
            name='MedicalProceduresList',
        ),
        migrations.RemoveField(
            model_name='medicalcategories',
            name='Moderator',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Is_Admin',
        ),
        migrations.AddField(
            model_name='users',
            name='Is_Moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CategoriesProcedures',
        ),
        migrations.DeleteModel(
            name='MedicalCategories',
        ),
        migrations.DeleteModel(
            name='MedicalProcedures',
        ),
        migrations.AddField(
            model_name='trauma',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Creator', to='bmstu_lab.users'),
        ),
        migrations.AddField(
            model_name='trauma',
            name='First_aid_in_Trauma_List',
            field=models.ManyToManyField(through='bmstu_lab.First_aid_Trauma', to='bmstu_lab.first_aid'),
        ),
        migrations.AddField(
            model_name='trauma',
            name='Moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Moderator', to='bmstu_lab.users'),
        ),
        migrations.AddField(
            model_name='first_aid_trauma',
            name='Trauma_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.trauma'),
        ),
    ]
