# Generated by Django 4.2.5 on 2023-12-12 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_first_aid_first_aid_trauma_trauma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trauma',
            name='Date_Approving',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Approving (Trauma)'),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_Creation',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Creating of the order (Trauma)'),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_End',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of End order (Trauma)'),
        ),
    ]
