# Generated by Django 4.2.5 on 2023-12-12 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0006_alter_trauma_date_approving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trauma',
            name='Date_Approving',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Approving (Trauma)'),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_Creation',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Creating of the order (Trauma)'),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_End',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of End order (Trauma)'),
        ),
    ]
