# Generated by Django 4.2.5 on 2023-12-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0007_alter_trauma_date_approving_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trauma',
            name='Trauma_Name',
        ),
    ]
