# Generated by Django 4.2.5 on 2023-12-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0008_remove_trauma_trauma_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_aid_trauma',
            name='Number',
            field=models.IntegerField(default=1, help_text='Sequence Number', null=True),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_Approving',
            field=models.DateTimeField(help_text='Date of Approving (Trauma)'),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_End',
            field=models.DateTimeField(help_text='Date of End order (Trauma)'),
        ),
    ]
