# Generated by Django 4.2.5 on 2023-12-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0009_alter_first_aid_trauma_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trauma',
            name='Date_Approving',
            field=models.DateTimeField(blank=True, help_text='Date of Approving (Trauma)', null=True),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Date_End',
            field=models.DateTimeField(blank=True, help_text='Date of End order (Trauma)', null=True),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='Moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID_Moderator', to='bmstu_lab.users'),
        ),
    ]
