# Generated by Django 4.2.5 on 2024-01-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0012_trauma_confirmation_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trauma',
            old_name='confirmation_doctor',
            new_name='Confirmation_doctor',
        ),
    ]
