# Generated by Django 4.2.5 on 2024-01-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0013_rename_confirmation_doctor_trauma_confirmation_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trauma',
            old_name='Confirmation_doctor',
            new_name='Confirmation_Doctor',
        ),
    ]
