# Generated by Django 4.2.5 on 2024-01-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0019_alter_trauma_confirmation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trauma',
            name='Confirmation_Doctor',
            field=models.CharField(choices=[('Pending', 'Ожидается'), ('Confirmed', 'Подтверждено'), ('Rejected', 'Отклонено')], default=None, help_text='Verbal confirmation of the Trauma', max_length=20, null=True),
        ),
    ]
